server:
  port: 8080

spring:
  profiles:
    default: dev

  datasource: # 실제 사용 application 과는 다른 설정. 구조는 거의 동일.
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: dongeon110
    password: 1234

  jpa:
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

mybatis:
  type-aliases-package: com.note.dbdocs.dto,com.note.dbdocs.vo
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info